### ISSUE TITLE
Sample App doesn't run and library doesn't seem to work

### ISSUE THREAD

**Issue by CarlosEsco** [jeziellago/compose-markdown#10]
Trying to run the sample app results in
```
Process: dev.jeziellago.compose.markdown, PID: 7234
    java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:808)
        at android.view.View.dispatchAttachedToWindow(View.java:22010)
```

Copying the example in the readme to a separate app results in no markdown actually being processed

**Comment by jeziellago** [comment]
Hi @CarlosEsco 
Thanks for reporting!
It was fixed.
