### ISSUE TITLE
java.lang.IllegalStateException: Unsupported

### ISSUE THREAD

**Issue by JackuXL** [jeziellago/compose-markdown#21]
java.lang.IllegalStateException: Unsupported
        at coil.util.-Utils.unsupported(Utils.kt:208)
        at coil.ImageLoader$Builder.availableMemoryPercentage(ImageLoader.kt:538)
        at dev.jeziellago.compose.markdowntext.MarkdownTextKt.createMarkdownRender(MarkdownText.kt:124)
        at dev.jeziellago.compose.markdowntext.MarkdownTextKt.MarkdownText-2NoNlqI(MarkdownText.kt:50)
        at space.technet.store.ui.activity.AppDetailActivity$onCreate$1$1$1.invoke(AppDetailActivity.kt:37)
        at space.technet.store.ui.activity.AppDetailActivity$onCreate$1$1$1.invoke(AppDetailActivity.kt:34)

**Comment by JackuXL** [comment]
My Code:
MarkdownText("1")

Gradle:
    implementation "io.coil-kt:coil:2.0.0-rc03"
    implementation "io.coil-kt:coil-compose:2.0.0-rc03"

    implementation 'com.github.jeziellago:compose-markdown:0.2.9'

**Comment by ohwittmannone** [comment]
I'm also having the same issue, is there an update?

**Comment by jeziellago** [comment]
Hello folks,
This error happens because Coil removed these methods.
```
     availableMemoryPercentage()
     bitmapPoolPercentage()
```
For a while, I will remove their usage backing to the default config.
