### ISSUE TITLE
Update to support Coil 2.x

### ISSUE THREAD

**Issue by CarlosEsco** [jeziellago/compose-markdown#22]
Attempting to use the library on a Coil 2.x project results in 

```
 java.lang.IllegalStateException: Unsupported
        at coil.util.-Utils.unsupported(Utils.kt:227)
        at coil.ImageLoader$Builder.availableMemoryPercentage(ImageLoader.kt:538)
        at dev.jeziellago.compose.markdowntext.MarkdownTextKt.createMarkdownRender(MarkdownText.kt:124)
        at dev.jeziellago.compose.markdowntext.MarkdownTextKt.MarkdownText-2NoNlqI(MarkdownText.kt:50)
```

**Comment by ohwittmannone** [comment]
I'm also experiencing this error

**Comment by jeziellago** [comment]
Duplicated: #21
