### ISSUE TITLE
MarkdownText not working on beta07

### ISSUE THREAD

**Issue by nglauber** [jeziellago/compose-markdown#6]
Library is not working on compose beta07 using Android Studio Arctic Fox | 2020.3.1 Beta 2. 

Here's the stack trace:
```
2021-05-22 21:08:19.732 10757-10757/br.com.nglauber.jetpackcomposeplayground E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.nglauber.jetpackcomposeplayground, PID: 10757
    java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer; in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/br.com.nglauber.jetpackcomposeplayground-pz_qCwlFrnIUpw_qmcHJAQ==/base.apk)
        at dev.jeziellago.compose.markdowntext.MarkdownTextKt.MarkdownText-PL9yxUQ(MarkdownText.kt:43)
        at br.com.nglauber.jetpackcomposeplayground.screens.Form2ScreenKt.Form2Screen(Form2Screen.kt:61)
        at br.com.nglauber.jetpackcomposeplayground.ComposableSingletons$MainActivityKt$lambda-8$1.invoke(MainActivity.kt:44)
        at br.com.nglauber.jetpackcomposeplayground.ComposableSingletons$MainActivityKt$lambda-8$1.invoke(MainActivity.kt:44)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.navigation.compose.NavHostKt$NavHost$6$1$1.invoke(NavHost.kt:134)
        at androidx.navigation.compose.NavHostKt$NavHost$6$1$1.invoke(NavHost.kt:133)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:59)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:50)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:46)
        at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:133)
        at androidx.navigation.compose.NavHostKt$NavHost$7.invoke(Unknown Source:13)
        at androidx.navigation.compose.NavHostKt$NavHost$7.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:96)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2139)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2402)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2554)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2525)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:555)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:733)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:102)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:443)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:415)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
2021-05-22 21:08:19.732 10757-10757/br.com.nglauber.jetpackcomposeplayground E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
This stackoverflow question might help ;) 
https://stackoverflow.com/questions/67611497/java-lang-nosuchmethoderror-after-upgrading-jetpack-compose-to-1-0-0-beta07/67651785#67651785

**Comment by jeziellago** [comment]
Hi @nglauber 👋🏻
I fixed on [v0.2.2](https://github.com/jeziellago/compose-markdown/releases/tag/0.2.2). Could you check it?
Thanks!

**Comment by nglauber** [comment]
It's fixed ;) Thanks @jeziellago!

**Comment by jeziellago** [comment]
Great!
